name: CDK app deployment

on:
    push:
        branches: ["PSDART-45342"]
jobs:
    aws_cdk:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v2
              with:
                fetch-depth: 2
            - name: Setup Node.js environment
              uses: actions/setup-node@v2
              with:
                node-version: 16
                cache: "npm"
            - name: Install root dependencies
              run: npm ci
            - name: Install dependencies
              working-directory: ./infra-vpc-cdk
              run: npm ci
            - name: Install AWS CDK
              run: npm i -g aws-cdk
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@master
              with:
                AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
            - name: Synth Check
              working-directory: ./infra-vpc-cdk
              run: cdk synth
            - name: Deploy stack
              working-directory: ./infra-vpc-cdk
              run: cdk deploy --all --require-approval never
